import * as THREE from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { ITEM_LIST } from '../src/data/items';
import { buildModel } from '../src/render/models';

const params = new URLSearchParams(location.search);
const page = Number(params.get('page') ?? 0);
const perPage = 30;
const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setSize(innerWidth, innerHeight);
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.shadowMap.enabled = true;
document.body.appendChild(renderer.domElement);
const scene = new THREE.Scene();
scene.background = new THREE.Color('#2a2d31');
const pm = new THREE.PMREMGenerator(renderer);
scene.environment = pm.fromScene(new RoomEnvironment(), 0.04).texture;
scene.environmentIntensity = 0.6;
const sun = new THREE.DirectionalLight('#fff4e0', 2.2);
sun.position.set(-3, 6, -4);
sun.castShadow = true;
sun.shadow.mapSize.set(2048, 2048);
Object.assign(sun.shadow.camera, { left: -12, right: 12, top: 12, bottom: -12 });
scene.add(sun, new THREE.AmbientLight('#8090a0', 0.5));
const floor = new THREE.Mesh(new THREE.PlaneGeometry(60, 60), new THREE.MeshStandardMaterial({ color: '#55585c' }));
floor.rotation.x = -Math.PI / 2;
floor.receiveShadow = true;
scene.add(floor);
const defs = ITEM_LIST.slice(page * perPage, page * perPage + perPage);
const cols = 6;
const cell = 2.2;
defs.forEach((def, i) => {
  const m = buildModel(def, { label: def.id.startsWith('box') ? 'KITCHEN' : undefined, dirt: 0.2, seed: def.id });
  const maxDim = Math.max(...def.dims);
  const s = Math.min(1.6 / maxDim, 6);
  m.scale.setScalar(s);
  const x = (i % cols - (cols - 1) / 2) * cell;
  const z = Math.floor(i / cols) * cell - 4;
  m.position.set(x, (def.dims[1] * s) / 2, z);
  m.rotation.y = Math.PI + 0.5;
  scene.add(m);
  const c = document.createElement('canvas');
  c.width = 256; c.height = 40;
  const ctx = c.getContext('2d')!;
  ctx.fillStyle = '#fff'; ctx.font = '600 22px "Barlow Condensed", sans-serif'; ctx.textAlign = 'center';
  ctx.fillText(def.id, 128, 28);
  const t = new THREE.CanvasTexture(c);
  const lbl = new THREE.Mesh(new THREE.PlaneGeometry(2, 0.32), new THREE.MeshBasicMaterial({ map: t, transparent: true }));
  lbl.rotation.x = -Math.PI / 2;
  lbl.position.set(x, 0.01, z + 0.95);
  scene.add(lbl);
});
const cam = new THREE.PerspectiveCamera(42, innerWidth / innerHeight, 0.1, 100);
cam.position.set(0, 11, 9);
cam.lookAt(0, 0, 1.5);
document.fonts.ready.then(() => {
  renderer.render(scene, cam);
  (window as unknown as { __ready: boolean }).__ready = true;
});
