// Shared type definitions for the logic layer.
// Nothing in src/core, src/data or src/systems may import three.js or touch the DOM,
// so the whole simulation runs (and is tested) in plain Node.

export type Rarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary' | 'mythic' | 'unique';
export const RARITIES: Rarity[] = ['common', 'uncommon', 'rare', 'epic', 'legendary', 'mythic', 'unique'];

export type Category =
  | 'furniture' | 'electronics' | 'tools' | 'collectibles' | 'jewelry' | 'art' | 'music'
  | 'sports' | 'household' | 'fashion' | 'media' | 'toys' | 'documents' | 'container' | 'trash';

export type TrendTag =
  | 'retro_gaming' | 'vinyl' | 'cameras' | 'watches' | 'jewelry' | 'mid_century' | 'antiques'
  | 'tools' | 'sports' | 'comics_cards' | 'art' | 'fashion' | 'music_gear' | 'coins' | 'household' | 'electronics';

export type ExpertId = 'watchmaker' | 'antiques' | 'electronics' | 'collectibles' | 'music';

/** 0 Destroyed · 1 Poor · 2 Used · 3 Good · 4 Very Good · 5 Excellent · 6 Mint */
export type Condition = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type Vec3 = [number, number, number];

/** How an item is examined on the workbench. */
export type InspectProfile =
  | 'watch' | 'jewelry' | 'camera' | 'electronics' | 'console' | 'music' | 'art' | 'paper'
  | 'coins' | 'furniture' | 'fashion' | 'tools' | 'generic' | 'document';

export type ContainerKind = 'box' | 'tote' | 'drawers' | 'case' | 'trunk' | 'jewelrybox' | 'toolbox' | 'safe' | 'bag';

export interface ContainerSpec {
  kind: ContainerKind;
  slots: [number, number];
  /** Largest item volume (m³) that fits inside. */
  maxItemVolume: number;
  /** Category weight overrides for the contents. */
  lootBias?: Partial<Record<Category, number>>;
  secretChance?: number;
  locked?: boolean;
}

export type BonusKind = 'signed' | 'first_press' | 'rare_variant' | 'hidden_cash' | 'provenance';

export interface BonusSpec {
  chance: number;
  kind: BonusKind;
  mult: number;
  label: string;
}

export interface ItemDef {
  id: string;
  /** Identified English name (translated at display time). */
  name: string;
  /** Items in the same family look alike until inspected. */
  family?: string;
  /** Shown after partial inspection, e.g. "Possible Vintage Watch". */
  possibleName?: string;
  category: Category;
  rarity: Rarity;
  /** Market value in Good condition, authentic, clean and working. */
  baseValue: number;
  /** ± fraction rolled per instance. */
  variance: number;
  /** Size in metres [width, height, depth]. */
  dims: Vec3;
  weight: number;
  model: string;
  modelParams?: Record<string, string | number | boolean>;
  tags: TrendTag[];
  inspect: InspectProfile;
  expert: ExpertId | null;
  fakeChance?: number;
  /** Value multiplier when the instance is counterfeit. */
  fakeValue?: number;
  fakeName?: string;
  brokenChance?: number;
  repairCost?: number;
  cleanable?: boolean;
  /** Cleaning destroys value (coins, patina). */
  cleaningHurts?: boolean;
  conditionSensitivity?: number;
  /** Condition distribution override (weights for 0..6). */
  conditionWeights?: number[];
  collectorValue?: number;
  demand?: number;
  container?: ContainerSpec;
  /** Can hold other items on top (boxes on a dresser). */
  supportsStack?: boolean;
  /** Occludes line of sight only partially (chairs, bikes). */
  sparse?: boolean;
  /** Stands upright against a wall (mattress, rug roll, skis). */
  leans?: boolean;
  jackpot?: boolean;
  quest?: string;
  bonus?: BonusSpec;
  /** Not generated by loot tables (quest rewards, story items). */
  special?: boolean;
  flavor: string;
}

export interface Family {
  id: string;
  unknownName: string;
  /** Vague hint shown at level 0. */
  hint: string;
}

export interface ClueNote {
  /** English template, translated at display time. */
  k: string;
  p?: Record<string, string | number>;
  /** +1 supports authenticity, -1 suggests a fake, 0 neutral. */
  tone?: -1 | 0 | 1;
}

export interface ItemKnowledge {
  /** 0 unknown · 1 partially identified · 2 identified · 3 expert-appraised */
  idLevel: 0 | 1 | 2 | 3;
  conditionKnown: boolean;
  workingKnown: boolean;
  authKnown: boolean;
  bonusKnown: boolean;
  steps: string[];
  clues: ClueNote[];
}

export type ItemLocation = 'unit' | 'van' | 'garage' | 'display' | 'listed' | 'consigned' | 'sold' | 'disposed' | 'gifted';

export interface ItemInstance {
  uid: string;
  defId: string;
  condition: Condition;
  authentic: boolean;
  roll: number;
  dirt: number;
  broken: boolean;
  bonus: BonusKind | null;
  knowledge: ItemKnowledge;
  location: ItemLocation;
  unitId: string | null;
  costBasis: number;
  foundDay: number;
  fromSecret?: boolean;
  /** Contents of a locked safe, generated at unit creation. */
  lockedContents?: ItemInstance[];
  /** Hidden compartment contents (dressers, trunks). Travels with the item until someone checks. */
  secret?: ItemInstance[];
  secretChecked?: boolean;
  soldFor?: number;
  soldDay?: number;
  soldChannel?: SaleChannel;
  cleanedTimes?: number;
  repairedTimes?: number;
}

// ─── Storage units ────────────────────────────────────────────────────────────

export type UnitSizeId = '5x5' | '5x10' | '10x10' | '10x15' | '10x20';
export type UnitEventId = 'flood' | 'estate' | 'mystery' | 'collector' | 'trash';

export interface UnitBlueprint {
  id: string;
  name: string;
  description: string;
  sizes: UnitSizeId[];
  categoryWeights: Partial<Record<Category, number>>;
  rarityBoost: number;
  trashRatio: [number, number];
  fill: [number, number];
  /** Multiplier on the item count for this size (hoarders pack more in). */
  density: number;
  boxShare: number;
  damageChance: number;
  secretChance: number;
  dirt: [number, number];
  event: UnitEventId | null;
  minLevel: number;
  weight: number;
  /** Chance that a story item for an active quest shows up. */
  storyChance: number;
  labels: string[];
}

export interface PlacedItem {
  inst: ItemInstance;
  pos: Vec3;
  rotY: number;
  dims: Vec3;
  label?: string;
  contents?: ItemInstance[];
  /** Fraction of sample rays that reach the item from the doorway (0..1). */
  visibility: number;
  tarp?: number;
  onTopOf?: string;
}

export interface Tarp {
  center: Vec3;
  size: [number, number];
  height: number;
  color: string;
}

export interface UnitHiddenStats {
  hiddenValue: number;
  visibleValue: number;
  itemCount: number;
  rareChance: number;
  damageChance: number;
  trashRatio: number;
  secretChance: number;
  risk: 'low' | 'medium' | 'high';
  bestItem: string | null;
}

export interface UnitData {
  id: string;
  number: string;
  /** Door position in the facility row (0-based, left to right). */
  slot: number;
  facilityId: string;
  blueprintId: string;
  event: UnitEventId | null;
  size: UnitSizeId;
  dims: { w: number; d: number; h: number };
  doorOpen: number;
  seed: number;
  tenant: string;
  monthsUnpaid: number;
  items: PlacedItem[];
  tarps: Tarp[];
  hidden: UnitHiddenStats;
  rumor: string | null;
}

// ─── NPCs & auction ──────────────────────────────────────────────────────────

export type NpcId = 'shark' | 'collector' | 'dealer' | 'rookie' | 'millionaire' | 'bluffer';
export type BidTiming = 'eager' | 'normal' | 'sniper' | 'random';

export type BarkKey =
  | 'arrive' | 'inspect_good' | 'inspect_bad' | 'inspect_item' | 'bid' | 'jump' | 'outbid_player'
  | 'drop' | 'win' | 'player_wins' | 'watching_player' | 'bluff' | 'stuck';

export interface NpcLook {
  skin: string;
  shirt: string;
  pants: string;
  hair: string;
  hat: 'none' | 'cap' | 'cowboy' | 'beanie' | 'fedora';
  hatColor: string;
  extra: 'none' | 'sunglasses' | 'pearls' | 'clipboard' | 'backpack' | 'tie' | 'chain';
  build: number;
  height: number;
}

export interface NpcProfile {
  id: NpcId;
  name: string;
  nickname: string;
  bio: string;
  look: NpcLook;
  budget: number;
  attendChance: number;
  bidRatio: [number, number];
  expertise: number;
  expertiseBy: Partial<Record<Category, number>>;
  affinity: Partial<Record<Category, number>>;
  timing: BidTiming;
  fever: number;
  observant: number;
  bluff: number;
  jumpChance: number;
  paddle: number;
  barks: Partial<Record<BarkKey, string[]>>;
}

export interface LotResult {
  unitId: string;
  winner: NpcId | 'player' | null;
  price: number;
  playerBid: number;
  trueValue: number;
}

export interface AuctionDayState {
  day: number;
  facilityId: string;
  lots: UnitData[];
  results: LotResult[];
  index: number;
  attendees: NpcId[];
  budgets: Record<string, number>;
  started: boolean;
  finished: boolean;
}

// ─── Economy, market ─────────────────────────────────────────────────────────

export type LedgerKind =
  | 'auction' | 'travel' | 'transport' | 'disposal' | 'cleaning' | 'repair' | 'expert' | 'locksmith'
  | 'sale' | 'fee' | 'bills' | 'upgrade' | 'job' | 'loan' | 'reward' | 'lab' | 'misc';

export interface LedgerEntry {
  day: number;
  amount: number;
  kind: LedgerKind;
  unitId?: string | null;
  itemUid?: string;
  note?: string;
}

export type SaleChannel = 'pawn' | 'online' | 'auction_house' | 'collector' | 'private';

export interface Listing {
  itemUid: string;
  price: number;
  listedDay: number;
  views: number;
  watchers: number;
}

export interface Consignment {
  itemUid: string;
  consignedDay: number;
  saleDay: number;
  reserve: number;
}

export interface CollectorRequest {
  id: string;
  collector: string;
  tag: TrendTag | null;
  category: Category | null;
  family: string | null;
  minRarity: Rarity;
  minCondition: Condition;
  premium: number;
  expires: number;
}

export interface BuyerOffer {
  id: string;
  itemUid: string;
  buyer: string;
  personality: BuyerPersonality;
  offer: number;
  maxPay: number;
  patience: number;
  expires: number;
}

export type BuyerPersonality = 'lowballer' | 'fair' | 'enthusiast' | 'impatient' | 'hardball';

export interface MarketEvent {
  tag: TrendTag;
  mult: number;
  until: number;
  headline: string;
}

export interface MarketState {
  trends: Record<TrendTag, number>;
  history: Record<TrendTag, number[]>;
  events: MarketEvent[];
  listings: Listing[];
  consignments: Consignment[];
  requests: CollectorRequest[];
  offers: BuyerOffer[];
}

export interface NewsItem {
  day: number;
  text: string;
  p?: Record<string, string | number>;
  kind: 'market' | 'sale' | 'rumor' | 'info' | 'warning' | 'quest';
}

// ─── Progression, quests ─────────────────────────────────────────────────────

export interface Stats {
  unitsWon: number;
  unitsLost: number;
  auctionsAttended: number;
  totalSpent: number;
  totalEarned: number;
  bestFind: { name: string; value: number } | null;
  worstPurchase: { unit: string; profit: number } | null;
  bestPurchase: { unit: string; profit: number } | null;
  rarestItem: { name: string; rarity: Rarity } | null;
  highestSale: { name: string; value: number } | null;
  itemsDiscovered: number;
  rareItemsFound: number;
  fakesFound: number;
  secretsFound: number;
  itemsSold: number;
  itemsRepaired: number;
  itemsCleaned: number;
  unitsProfitable: number;
  unitsLosing: number;
  jackpots: number;
  negotiationsWon: number;
  bestNegotiation: number;
  vanFills: number;
  finalCallWins: number;
  sharkBeaten: number;
  cleanSweeps: number;
}

export interface QuestState {
  id: string;
  stage: number;
  found: string[];
  resolved: string | null;
  startedDay: number;
  pity: number;
  developed: boolean;
}

export interface DiscoveryRecord {
  count: number;
  best: number;
  firstDay: number;
}

export interface SearchState {
  unitId: string;
  taken: string[];
  opened: string[];
  tossed: string[];
  tarpsPulled: number[];
  trips: number;
  transportCost: number;
}

export interface UnitRecord {
  id: string;
  number: string;
  blueprintId: string;
  event: UnitEventId | null;
  size: UnitSizeId;
  day: number;
  price: number;
  trueValue: number;
  status: 'searching' | 'cleared';
  itemUids: string[];
  disposed: number;
}

export interface GarageState {
  upgrades: string[];
  wall: string;
  floor: string;
  light: string;
  neon: string | null;
  display: (string | null)[];
}

export interface VehicleState {
  id: string;
  upgrades: string[];
}

export interface GameState {
  version: number;
  createdAt: number;
  savedAt: number;
  seed: number;
  day: number;
  money: number;
  xp: number;
  facilityId: string;
  items: Record<string, ItemInstance>;
  garage: GarageState;
  vehicle: VehicleState;
  market: MarketState;
  today: AuctionDayState | null;
  search: SearchState | null;
  searchUnit: UnitData | null;
  units: Record<string, UnitRecord>;
  ledger: LedgerEntry[];
  stats: Stats;
  achievements: Record<string, number>;
  quests: Record<string, QuestState>;
  discovered: Record<string, DiscoveryRecord>;
  rivalry: Record<string, number>;
  news: NewsItem[];
  flags: Record<string, boolean>;
  uid: number;
  loan: { principal: number; due: number } | null;
}
